# Site settings
title: kmARC
email: ---
description: 
baseurl: /blog

github_username:  kmARC11
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
